repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/realm/SwiftLint
    rev: 0.52.2
    hooks:
      - id: swiftlint
        entry: swiftlint --fix --strict
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.51.11
    hooks:
      - id: swiftformat
